language: node_js
node_js:
- '5'
branches:
  only:
  - source
before_script:
- git config --global user.name 'fitzlee'
- git config --global user.email 'fitz.lee@outlook.com'
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  
install:
- npm install
script:
- hexo generate
- hexo deploy --silent
env:
  global:
    secure: aFt+q5gj0yNkvTSmq93JpMIVOttO4xXvV7rURphN5s+6Lz2tP8ol1tX7lDzvsU2fmfqHnWQJeTsmtDLwy0tMX+nnQ55vgsH8jW0i+EhUTwjdldcVxW5+MeoPZwzpQYb2qdwEW0n5miol/mOtItG/Hmu+RyGHqaIMGVXRqHscqLcIHHRfSpySbKFR9IErhvkV9vXkBzd6oz8MsVo2RWKTpyG9mg9j74pfgHMId7p4eZGUCRQnIJXQleuYnBIoogdL4fmcjs+ElqKn2x1RUcEvZ+2YIqVLF4EJYLaqNA9LQYJFjfCziocu49S5q3IdhwFrMFeof0BbJD6NRC2pMG0fZVFh5kWHczO5BAh6TWJNoNN5PsofqwjjX9dxjOeJeuT9qWPg/ceCdCGD/FtMKTsn1IIBOHPF5ifIeX1KixeKYpec8HLQVKyEt6Hc5OkoYfnhSfQ/Gvn/W0jpf14S1Hq8+n2tRp7zbyvfhKUM4jqGhURTAjJW7j+LOl1Di9pjU+l/HaE/f0r5Atrw841XvV9DnFMGLMg8Ml4l1lLL2v0rtrOPMqx45wIpK3N/IHsnHsjGAIznE3YyAF6B7L1Hjd22v4UxIu/JNszQxcXu10CwAqsI6ZwjnpM/vmEkEfGR/glTg0RvDnhYw/zct3DzZHg9hGtDktXRL81dhbqrxGayZD0=
