language: node_js
node_js: stable

install:
  - npm install

before_script:
  - git config user.name 'fitzlee'
  - git config user.email 'fitz.lee@outlook.com'

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git add -A
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" HEAD:master

branches:
  only:
    - source

env:
 global:
   - GH_REF: github.com/fitzlee/FitzLee.github.io.git