# Blog info
blog_name: Fitz Lee
slogan: 不畏将来，不念过去，不怨现在
url: http://fitzlee.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: 专注Android & Security,崇尚Smart Life,信仰The Wind Rises

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: false # true:在新页面打开
  - name: Github
    url: https://github.com/fitzlee
    target_blank: true
#  - name: Zhihu
#    url: https://www.zhihu.com/people/fitzlee
#    target_blank: true 
#  - name: Twitter
#    url: https://twitter.com/forsigner
#    target_blank: true

# config page nav
page_nav:
  - name: Blog
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: Category
    url: /category/
    target_blank: false
  - name: Tag
    url: /tag/
    target_blank: false
#  - name: 友链
#    url: /link/
#    target_blank: false
  - name: About
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: Search
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Menu

search_slogan:
  isShow: false # true|fase
  text: Could you find the happiness of world ~

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件 leefits@gmail.com

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持fitzlee
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
#baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
disqus_shortname: fitzlee
# duoshuo_shortname: forsigner


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "全栈工程师，常用 Java / Android / C."
    #- "遇山过山，遇雨撑伞，有桥桥渡，无桥自渡，淡若清风，含笑走过."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@fitzlee"
    text_value_url: https://github.com/fitzlee
#  - type: weibo
#    icon: icon-weibo
#    text_key: 微博
#    text_value: "@forsigner"
#    text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "fitz.lee@outlook.com"
    text_value_url: mailto:fitz.lee@outlook.com
  - type: location
    icon: icon-location
    text_value: Shanghai

link:
  - name: fitzlee
    info: 专注Android & Security,崇尚Smart Life,信仰The Wind Rises
    url: http://fitzlee.github.io
    avatar: /images/avatar.jpg

project:
  - type: opensource
    name: XWiki-android-authenticator
    url: https://github.com/xwiki-contrib/android-authenticator
    intro: An Android authenticator to be used by other andoid application and with integrated synchronisation of contacts
  - type: personal
    name: Android Guru
    url: https://github.com/fitzlee/GuruAndroid
    intro: learn Android... Demo_source&Document
  - type: personal
    name: WebJavaJs
    url: https://github.com/fitzlee/WebJavaJs
    intro: Java Web & Node Js (SpringMVC Mybatis Anjular AmazeUI)
  - type: personal
    name: JNIDemo
    url: https://github.com/fitzlee/JNIDemo
    intro: A Java & Android JNI Demo, Just For Learning & Coding Quickly